### ISSUE TITLE
Bug Found: You can go back to previous check points

### ISSUE THREAD

**Issue by hardikjumnani** [Shashankdixitt/Line-chaser#1]
How I created the bug: When I was in checkpoint 3, I moved back to checkpoint 2 and the score also turned to -10. Also a Game Over! message came when this happened, but I was still able to play. ({Seems like you implementing Ready Player One level Easter Eggs})

![image](https://github.com/Shashankdixitt/Line-chaser/assets/76278623/3c9ba918-ba3e-4b4e-a10e-ac6564bf49b4)

**Comment by Shashankdixitt** [comment]
Thanks Hardik for pointing this, totally missed this.
Will cover this bug in next Update and In next update I will converting this with Javascript so that It can be playable in browser and add 10differnet level and maps

**Comment by Shashankdixitt** [comment]
And If needed You can fork the repo and try your hands on it But after Your Scaler NSET Exam 🫡🫂

**Comment by hardikjumnani** [comment]
Sure bro, will definitely be a helping hand in this project! :)
